name: 'Cache sync'
description: 'Cache sync'
inputs:
  cache-volume:
    description: "Cache volume name"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sync Docker cache
      shell: bash
      run: |
        CACHE_DIR="/mnt/${{ inputs.cache-volume }}"
        if ! command -v docker >/dev/null; then
            echo "Docker is not installed, skipping cache sync"
            exit 0
        fi
        if [ -d "$CACHE_DIR" ]; then
            DOCKER_CACHE_DIR="$CACHE_DIR/docker"
  
            echo "Stopping containers and cleaning up..."
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -fv $(sudo docker ps -a -q) || true

            echo "Stopping Docker daemon"
            sudo systemctl stop docker
            sudo sync

            echo "Syncing docker folders to cache"
            sudo mkdir -p "$DOCKER_CACHE_DIR"

            if sudo test -d "/var/lib/docker/overlay2"; then
                sudo mkdir -p "$DOCKER_CACHE_DIR/overlay2"
                targets=$(sudo find "/var/lib/docker/overlay2" -mindepth 1 -maxdepth 1)
                if [ -z "$targets" ]; then
                    echo "⚠️  No entries found in /var/lib/docker/overlay2 — skipping"
                else
                    for target in $targets; do
                        id=$(basename "$target")
                        if [ ! -f /etc/docker-cache-mounts ] || ! grep -Fxq "$target" /etc/docker-cache-mounts; then
                            sudo rsync -aH --delete "$target/" "$DOCKER_CACHE_DIR/overlay2/$id/"
                        fi
                    done
                fi
            fi

            for DIR in image buildkit; do
                sudo rsync -aH --delete "/var/lib/docker/$DIR/" "$DOCKER_CACHE_DIR/$DIR/"
            done
            sudo sync
        else
            echo "$CACHE_DIR not available — skipping Docker cache sync"
        fi
